customCommands:
  - key: "<c-a>" # ctrl + a
    context: "files"
    command: 'generate-commit-message > .git/AI_COMMIT_MESSAGES'
    loadingText: "Generating commit message with Copilot..."
  - key: "<c-g>"
    context: "files"
    command: 'git commit -m "{{.Form.Msg}}" --no-verify'
    prompts:
      - type: "menuFromCommand"
        title: "ai Commits"
        key: "Msg"
        command: "cat .git/AI_COMMIT_MESSAGES"
        filter: '^(?P<number>\d+)\.\s(?P<message>.+)$'
        valueFormat: "{{ .message }}"
        labelFormat: "{{ .number }}: {{ .message | green }}"

